package br.com.stling.bean;

import java.math.BigDecimal;

// Generated 14/08/2017 17:30:55 by Hibernate Tools 5.2.1.Final

/**
 * Billing generated by hbm2java
 */
public class Produto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String descricao;
	private BigDecimal valor;

	public Produto() {
	}
	
	public Produto(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}
	
	

	public static long getSerialversionuid() {
		return serialVersionUID;
	}	
}
