package br.com.stling.bean;
// Generated 14/08/2017 17:30:55 by Hibernate Tools 5.2.1.Final

/**
 * Billing generated by hbm2java
 */
public class TipoUsuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String descricao;

	public TipoUsuario() {
	}
	
	public TipoUsuario(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}	
}
